# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/yw980/code/classManager/UI/Stuhealthy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_StuHealthy(object):
    def setupUi(self, StuHealthy):
        StuHealthy.setObjectName("StuHealthy")
        StuHealthy.resize(1581, 900)
        self.widget = QtWidgets.QWidget(StuHealthy)
        self.widget.setGeometry(QtCore.QRect(421, 819, 551, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SaveButton = PrimaryPushButton(self.widget)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)
        self.changeButton = PrimaryPushButton(self.widget)
        self.changeButton.setObjectName("changeButton")
        self.horizontalLayout.addWidget(self.changeButton)
        self.returnButton = PrimaryPushButton(self.widget)
        self.returnButton.setObjectName("returnButton")
        self.horizontalLayout.addWidget(self.returnButton)
        self.SaveButton_2 = PrimaryPushButton(self.widget)
        self.SaveButton_2.setObjectName("SaveButton_2")
        self.horizontalLayout.addWidget(self.SaveButton_2)
        self.widget1 = QtWidgets.QWidget(StuHealthy)
        self.widget1.setGeometry(QtCore.QRect(150, 30, 1251, 721))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.YearBox = SpinBox(self.widget1)
        self.YearBox.setMinimum(2020)
        self.YearBox.setMaximum(2048)
        self.YearBox.setProperty("value", 2024)
        self.YearBox.setObjectName("YearBox")
        self.horizontalLayout_2.addWidget(self.YearBox)
        self.queryYearButton = PrimaryPushButton(self.widget1)
        self.queryYearButton.setObjectName("queryYearButton")
        self.horizontalLayout_2.addWidget(self.queryYearButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.queryChildButton = PrimaryPushButton(self.widget1)
        self.queryChildButton.setObjectName("queryChildButton")
        self.horizontalLayout_3.addWidget(self.queryChildButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.TableWidget = TableWidget(self.widget1)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.TableWidget, 1, 0, 1, 2)

        self.retranslateUi(StuHealthy)
        QtCore.QMetaObject.connectSlotsByName(StuHealthy)

    def retranslateUi(self, StuHealthy):
        _translate = QtCore.QCoreApplication.translate
        StuHealthy.setWindowTitle(_translate("StuHealthy", "学生体检管理系统"))
        self.SaveButton.setText(_translate("StuHealthy", "保存"))
        self.changeButton.setText(_translate("StuHealthy", "修改"))
        self.returnButton.setText(_translate("StuHealthy", "返回"))
        self.SaveButton_2.setText(_translate("StuHealthy", "导出"))
        self.queryYearButton.setText(_translate("StuHealthy", "查询"))
        self.lineEdit.setText(_translate("StuHealthy", "请输入要查找幼儿的姓名"))
        self.queryChildButton.setText(_translate("StuHealthy", "查询"))
from qfluentwidgets import PrimaryPushButton, SpinBox, TableWidget
