# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/yw980/code/classManager/UI/Thingsquery.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_ThingsQuery(object):
    def setupUi(self, ThingsQuery):
        ThingsQuery.setObjectName("ThingsQuery")
        ThingsQuery.resize(1400, 900)
        self.layoutWidget = QtWidgets.QWidget(ThingsQuery)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 60, 1071, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.queryChildButton = PrimaryPushButton(self.layoutWidget)
        self.queryChildButton.setObjectName("queryChildButton")
        self.gridLayout.addWidget(self.queryChildButton, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.TableWidget = TableWidget(self.layoutWidget)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.TableWidget, 1, 0, 1, 3)
        self.layoutWidget1 = QtWidgets.QWidget(ThingsQuery)
        self.layoutWidget1.setGeometry(QtCore.QRect(421, 819, 551, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SaveButton = PrimaryPushButton(self.layoutWidget1)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)
        self.deleteButton = PrimaryPushButton(self.layoutWidget1)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.returnButton = PrimaryPushButton(self.layoutWidget1)
        self.returnButton.setObjectName("returnButton")
        self.horizontalLayout.addWidget(self.returnButton)
        self.SaveButton_2 = PrimaryPushButton(self.layoutWidget1)
        self.SaveButton_2.setObjectName("SaveButton_2")
        self.horizontalLayout.addWidget(self.SaveButton_2)

        self.retranslateUi(ThingsQuery)
        QtCore.QMetaObject.connectSlotsByName(ThingsQuery)

    def retranslateUi(self, ThingsQuery):
        _translate = QtCore.QCoreApplication.translate
        ThingsQuery.setWindowTitle(_translate("ThingsQuery", "物资管理系统"))
        self.queryChildButton.setText(_translate("ThingsQuery", "查询"))
        self.lineEdit.setText(_translate("ThingsQuery", "请输入要查找物品的名字"))
        self.SaveButton.setText(_translate("ThingsQuery", "保存"))
        self.deleteButton.setText(_translate("ThingsQuery", "删除"))
        self.returnButton.setText(_translate("ThingsQuery", "返回"))
        self.SaveButton_2.setText(_translate("ThingsQuery", "导出"))
from qfluentwidgets import PrimaryPushButton, TableWidget
